const styles = {
  container: {
    display: 'flex',
    height: '93vh',
    // width: '100vw',
    backgroundColor: '#020617',
    color: '#f8fafc',
    fontFamily: 'sans-serif',
    overflow: 'hidden',
  },
  sidebar: {
    width: '25%',
    height: '100%',
    backgroundColor: '#0f172a',
    borderRight: '1px solid #1e293b',
    padding: '24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    overflowY: 'auto',
    zIndex: 20,
  },
  main: {
    width: '75%',
    height: '100%',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    background: '#020617',
    overflow: 'hidden',
  },
  label: {
    fontSize: '10px',
    fontWeight: '800',
    color: '#475569',
    textTransform: 'uppercase',
    letterSpacing: '0.15em',
    marginBottom: '8px',
    display: 'block',
  },
  select: {
    width: '100%',
    padding: '12px',
    borderRadius: '10px',
    backgroundColor: '#1e293b',
    border: '1px solid #334155',
    color: '#f8fafc',
    outline: 'none',
    fontSize: '14px',
  },
  questCard: {
    padding: '12px',
    borderRadius: '12px',
    backgroundColor: '#1e293b',
    border: '1px solid #334155',
    marginBottom: '8px',
    cursor: 'pointer',
    position: 'relative',
    transition: 'border-color 0.2s ease',
  },
  marker: {
    position: 'absolute',
    width: '12px',
    height: '12px',
    borderRadius: '50%',
    border: '1px solid white',
    boxShadow: '0 0 8px rgba(0,0,0,0.8)',
    zIndex: 30,
    cursor: 'default'
  },
  descriptionMarker: {
    position: 'absolute',
    borderRadius: '5px',
    border: '1px solid white',
    boxShadow: '0 0 8px rgba(255, 255, 255, 0.8)',
    width: "300px",
    padding: "2px",
    zIndex: 30,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    background: 'black',
    fontSize: '15px',
    fontWeight: 'bold',
    color: 'white',
    cursor: 'pointer'
  },
  extractMarker: {
    position: 'absolute',
    width: '20px',
    height: '20px',
    boxShadow: '0 0 8px rgba(0,0,0,0.8)',
    zIndex: 28,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '10px',
    fontWeight: 'bold',
    color: 'black',
    cursor: 'help'
  },
  origin: {
    position: 'absolute',
    width: '20px',
    height: '20px',
    border: '1px solid #ef4444',
    borderRadius: '50%',
    pointerEvents: 'none',
    zIndex: 25,
  },
  originLine: {
    position: 'absolute',
    backgroundColor: 'rgba(239, 68, 68, 0.3)',
    pointerEvents: 'none',
    zIndex: 24,
  },
  zoomControls: {
    position: 'absolute',
    bottom: '24px',
    left: '24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    zIndex: 50,
  },
  zoomBtn: {
    width: '40px',
    height: '40px',
    borderRadius: '8px',
    backgroundColor: 'rgba(15, 23, 42, 0.9)',
    border: '1px solid #334155',
    color: '#f8fafc',
    fontSize: '12px',
    fontWeight: 'bold',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backdropFilter: 'blur(8px)',
  },
  calibrationBtn: {
    width: '40px',
    height: '40px',
    borderRadius: '8px',
    border: '1px solid #334155',
    color: '#f8fafc',
    fontSize: '12px',
    fontWeight: 'bold',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backdropFilter: 'blur(8px)',
  },
  coordBox: {
    position: 'absolute',
    top: '24px',
    right: '24px',
    backgroundColor: 'rgba(15, 23, 42, 0.8)',
    padding: '10px 16px',
    borderRadius: '10px',
    border: '1px solid #334155',
    backdropFilter: 'blur(8px)',
    zIndex: 50,
  },
  calibrationPanel: {
    position: 'absolute',
    bottom: '24px',
    right: '24px',
    backgroundColor: 'rgba(15, 23, 42, 0.9)',
    padding: '16px',
    borderRadius: '12px',
    border: '1px solid #334155',
    zIndex: 50,
    width: '280px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    backdropFilter: 'blur(10px)',
  },
  checkboxRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '11px',
    color: '#cbd5e1',
    cursor: 'pointer',
  },
  controlRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  inputNumber: {
    width: '80px',
    backgroundColor: '#020617',
    border: '1px solid #334155',
    borderRadius: '4px',
    color: '#60a5fa',
    fontSize: '11px',
    padding: '2px 4px',
    outline: 'none',
  },
  btnSmall: {
    backgroundColor: '#2563eb',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    padding: '4px 8px',
    fontSize: '10px',
    fontWeight: 'bold',
    cursor: 'pointer',
    marginTop: '4px'
  },
};

export default styles;